language: node_js
sudo: false

node_js:
  - 5.3.0

env:
  -
    DEBUG=*
    PORT=3100
    TEST_SERVICE_URL=http://localhost:3100

before_script:
  - make install build
  - node build/mount &
  - sleep 5

script:
  - make test

cache:
  directories:
    - node_modules
    - typings
