language: node_js
sudo: false

addons:
  postgresql: 9.4

node_js:
  - 5.3.0

env:
  -
    CP_ALLOW_APIKEY_AUTH=1
    DATABASE_URL=postgres://postgres@localhost:5432/travis_ci_test
    DEBUG=*
    LINKEDIN_CLIENT_ID=fakedontmatter
    LINKEDIN_CLIENT_SECRET=fakedontmatter
    PORT=3100
    TEST_AUTH_URL=http://localhost:3100/auth
    TEST_SERVICE_URL=http://localhost:3100

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - make install build
  - node build/mount &
  - sleep 5
  - make seed
  - ./scripts/generate user

script:
  - make test

cache:
  directories:
    - node_modules
    - typings
