language: node_js
sudo: false

node_js:
  - 5.3.0

services:
  - postgresql
  - mongodb

addons:
  postgresql: 9.4

cache:
  directories:
    - node_modules
    - typings

env:
  global:
    - PORT=3000
    - CP_ALLOW_APIKEY_AUTH=1
    - CP_PURGE_KEY=allowall
    - CP_TEST_INSTANCE_URL=http://localhost:3000
    - DATABASE_URL=postgres://postgres@localhost:5432/travis_ci_test
    - MONGO_URL=mongodb://localhost:27017/test
    - LINKEDIN_CLIENT_ID=fakedontmatter
    - LINKEDIN_CLIENT_SECRET=fakedontmatter
    # EMBEDLY_API_KEY
    - secure: "HYlDPTVWx6XUF1sr9elIMP9aSUtTqhgcNarcQJ6oofIA1HIGCQxS92V8bbS4YKaaEXTOlJDVedxaSCJSZ9aG1JhKSgkeW6mAUqEPZ5x+CHYYaHhPTqLwQfAc86+F5pYADuKAtIkIB+pwiVIX81XBhc/StazGw22/VNgRmfN7qwSY+2HpRyboRseIw1/9PQmj/tx9F4cN3ttWdk4PytWEQcB43hxAeb37GVjwW7MJPvJ6LtBnmm/eTIjz71cN0QgpPtM01sPrEyR/RBcF+2Y8j3bYmTXex0fWMdz+CMNElC73qbohRVFnPNtV7Uoxpd5GuAqdKH3eHZ0/A0t/Q9Wu4ZPwM4riv6kRLHNjT51MfKrgU/5bArkyxaBUIq52ctYh9gKfHmOtd9VnRjj54BlDAn9hWfJ9gUmN//vBwjjSGCbFfaMWHOquVNEHO1BK27BFYkCn4XfrLkox+n5C56G5Dwlql9Q4bAzyqldpc2K2aZUeVrZ5/aPAZH3hblvWZl23w1ZsFX3TOQBrGlYLPV2AuEVKlmuqtlGXeWSIz0wH3HoT6XsZqpJPdy4kqVor7Tf9tR16PuIi4aDLP+ystNdelgSPPKEH+RVc4taxCoaV6E9P7qAgKWxG/hKdjPipTwfYUgHByAOQ7eCiDVHE+MwZtjNx1qdxizAOZZObC3x6Mnw="
    # TRELLO_KEY
    - secure: "iiOAcmeb5Vw4qikt1x4fTyp1abNp15bItgg1JVGhmyu9LrNgW0OFFB5kxUGJ35Oqervr3lamikCg+ZI2AcLlJpC1IwvPCU3buZkdIdqJcFcHNUjPb50DqVDxh8tFrFj9ivOxxWbyduuIHs0CGFdQlfQdCbuqjoofh90PXScpNyHq516J4J80thoPN/ox/xy8UV+plkGAc3EGoqM6fIaJcsOVnjrgKGUKy4L7WH98T9bmreKw9MB6IY35C8RRSOXM0qao1wCjXGekgSQL7C62RVdfAjKb9vwKwcnR2OkRexLnAeZKYqtFFlA8p0S+jzJWhGTOcZ0dAIZel/HMrMNqtpvx5lRDYPVgKuDVVWqawL0rjUeGhDec8TB6kmIHl6pFzQw++Piiyr3kjvYY8bkBzrL8ECgjNK3mTDst+vxz1VyiXUlCWVQUXaxRu5auuNDUErQoLFUGz99a6YFhRIRVgOgEPgueHmzJ1abBApa9OcvOpaoNYjtI1RCI60jsS4EzuMc9GNDokgTqzUDwJ+rUPbFj8IZCoiIkO8094fWXBAxBDkX70mxmzP3jND6yuX897uBee+EX1gaoPvSTJVJx0FE/zF5Ok+xEP86Wva0PQPKjEZllGExpavVJggZk7owOg86piuoZabHAsVXedrS7QZ4imWS/5D2seuN0qLHSCdw="
    # TROLLO_TOKEN
    - secure: "UQxJG2HWRKIAbDbcLi2sGvNlisP9ld8uuL3mwJYkO4YdmjaaFTQaviK3QUYkt+cGq2RTh8DETvmNLoKMG3HuN50CzUnLgGpHReUtPkbuQlECLBxNh4YUK2YnuUbpxCZyMze60vGna1W6VlD0JhkZ+Miz0nqXDzGWmFiJOv7Nn30ejcYFtnfUekuGfFRzeUwpxJPY6O4sMIFXCskCVZjUNrfB1Zv7SKblz3GnKVxoAsI/R8HXDAkDAGx58h2vQ1a8ElzclQ8saJGNPsF2bwvrWgGs5lLKxwy5yI6rcRTcil5aa7TVlf+YhHHldL7LKZ2SyAOQnxAmj/cQ7pOl04/FhI4t00BVe9kYfk2Uh2XwMFCU+jB30+9YYIILR+ng9FwzNxZPAzbWv/y8UYgXaLWb8PeXRAbHbkzgFY+WwRwGLsgN0yihVv8+ojo/2CZWL/CEoZkIjpLsdm1055ydJ0877WBNbTsuxkVmJOhhih6FV19xIylmJQZbthXMP1XN1bz7n1vDZJFBxFEhvvJ95rt58pAYwV8ak1/ySzg/VISjSosqOEt043QC6aPfwQPtaocGC7+eJGlNq7JZZCbu/910eelos8fZcRSYhbIBJgUPGVEnNgq6HhnaBN+P/2lKV3hSWUAZlOqYensuvViNKym3xOBM4eUZQ4Fvkh7/LsPa7VE="
    # TRELLO_LIST_ID
    - secure: "JFF5Nw+23SrZ6SOoumogaHv6NjIYbaqQjCAAbnXQBOZJggfQlw850ajf6V78lYwXHHcChkesmsUSVoD4Pb67IwSxJ1lbSUlBei83I/CGPSfTT4/+sQt8paKD1G/lLvn8Z6ADQX3kgx0rEs2e51kJXwDiWJgtmT+XYv3Yt5ENyocpOnVGuYSqE2+VKpf+eHHAA5Ms34eTcP/ATypIftd0o/2hSqEzxVPdzoB/vUr7lvAjaW6xAwhJooNqctLgkwLz1RdopsgR9l1YYAY1DGhGgHUa5//RnYLFlZ7ko7pjhhhEqa+jT0ZW040rKaWhsdIAEIg5z2lm2RpDI8w2PVi6w8XMpDaq0QfmNsnqNx6yHlQRTo+MFKqLWiViNHjZJckaCO+SqwlMlj6wt8bhHv4r4bw5tnAXf3TRm0Cke/RoRywYQpB+vGHt4+UAotH/A1RBIhTLoSxFHa1BD+xppllmY9K0/ayqPLEjK2HbAmjwMVWqRkwGG3rqJ/0is3reHhFvBFLXktqoZd0RjGnT9jds9Y1pFhSzMtpuKmh2HciOdQrbYqObijeDeziVfPzLR6dnnt5H6kZFAe28aCqqKqRUn+QrOECxV875LDMYunPPCE3/wuNox/uhUOvxpEM7FQWRXqOdj5YZMX2lDKB279wj8PiNg8KDjaE0SD/yRJS8iAM="
    # TRELLO_BOARD_ID
    - secure: "TjAuUoW8peyuIum/SB6pLn7EXQ+dUhJ4oNXKpXFe7IFMV0KaOF0re6Fp0VazOGILn2znxnOmi/X8C5Mafo1d5lz4b1kRKc9QLCldN0bCbhFHikCcr6UYDkGKnLhH+q4QIgGNoZYPFCkpu1oPjGyAjBLJ8z7uhoKRMmvbYmIXZwHdm52Pq3iMmWEqsHiarz5s162cLMbb7HvwJNHQeFjwMagV1nElsoK27jK4A7OJsp0DUih73PeXoqNRF0GX05f68OJXgKeCG/O1CrFLyvvV4uiSOevzX5LjLyLwaHkkpQWvj9o2Z2qHLPUtxSc6MujkRc/uXR8XgUG4B3UOfJwgjb6xM2uByssLeqHjcy+E0Vmg1j4Qn2fp1GHR1aon8+XKLQZDMkYRab3ZfrQmbHjwAIdV9qIvLQaa9YRYPwbrLv95ybNcPM+mSyvftWn4TlnLW7vmnH/E+xYguUFlYEWJXUM92/n1D/1HHK+2Wv/Mhc1Is5hwun+FpknYOJnU55wiulDiiBzB+BZhYsZo58gh/v9bqGvSuYYuciXIHlwhJtBxLxtvyUTN+NAP3YJ3gOZJ5e1N72jJB6ITRNGoYe9evdgPpAEDelEy94Yx3b99LiKpPuWaBCHQCRUIelplvDlBp3GfrnFmOddrHAvUHnjWko7EV9w/7/m/EqLkysSiLI4="

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - DEBUG=* make server &> server.log &
  - sleep 5
  - ./script/migration run
  - ./script/bootstrap base
  - ./script/bootstrap test

after_failure:
  - cat server.log

script:
  - make lint test
