nginx:
  build: config/nginx
  links:
    - "cp_server_1:cp_server_1"
  ports:
    - "80:80"

cp_server_1:
  build: src/server
  expose:
    - 3000
  volumes:
    - .:/home/app/client
  environment:
    - PORT=3000
    - DEBUG="*cp*"
