nginx:
  build: config/nginx
  links:
    - "server:server"
  ports:
    - "80:80"

postgres:
  build: config/postgres
  environment: &postgres_environment
    POSTGRES_DB: cp_db
    POSTGRES_PASSWORD: mysecret
    POSTGRES_USER: cp_user
    POSTGRES_HOST: postgres

elasticsearch:
  build: config/elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  expose:
    - 9200
    - 9300
  environment: &elasticsearch_environment
    ELASTICSEARCH_HOST: elasticsearch:9200

mongo:
  build: config/mongo
  environment: &mongo_environment
    MONGO_HOST: mongo
    MONGO_COLLECTION: cp_coll

rabbitmq:
  build: config/rabbitmq
  ports:
    - "15672:15672"
  environment: &rabbitmq_environment
    RABBITMQ_HOST: rabbitmq

server:
  build: .
  links:
    - postgres
    - mongo
    - rabbitmq
    - elasticsearch
  ports:
    - "3000:3000"
  expose:
    - 3000
  volumes:
    - .:/home/app/client
  env_file:
    - .env
  environment:
    <<: *postgres_environment
    <<: *mongo_environment
    <<: *rabbitmq_environment
    <<: *elasticsearch_environment
    PORT: 3000
