nginx:
  build: config/nginx
  links:
    - "cp_server_1:cp_server_1"
  ports:
    - "80:80"

postgres:
  image: postgres
  environment: &postgres_environment
    POSTGRES_PASSWORD: mysecret
    POSTGRES_USER: cp_user
    POSTGRES_DB: cp_db

cp_server_1:
  build: src/server
  links:
    - postgres
  ports:
    - "3000:3000"
  expose:
    - 3000
  volumes:
    - .:/home/app/client
  environment:
    <<: *postgres_environment
    PORT: 3000
    DEBUG: "*cp*"
