nginx:
  build: config/nginx
  links:
    - "cp_server_1:cp_server_1"
  ports:
    - "80:80"

postgres:
  build: config/postgres
  environment: &postgres_environment
    POSTGRES_DB: cp_db
    POSTGRES_PASSWORD: mysecret
    POSTGRES_USER: cp_user
    POSTGRES_HOST: postgres

mongo:
  build: config/mongo
  environment: &mongo_environment
    MONGO_HOST: mongo
    MONGO_COLLECTION: cp_coll

cp_server_1:
  build: src/server
  links:
    - postgres
    - mongo
  ports:
    - "3000:3000"
  expose:
    - 3000
  volumes:
    - .:/home/app/client
  environment:
    <<: *postgres_environment
    <<: *mongo_environment
    PORT: 3000
    DEBUG: "*cp*"
