user:
  admin:
    id: &user_admin_id 'a2a2c5ec-7eb3-4c7e-8615-9ab49343ed93'
    name: 'Admin Test User'
    raw_email: 'testing@consumr-project.org'
    role: 'admin'
    auth_apikey: 'b2df88fa-dd25-42ba-b456-3c8d164d3343'
    created_by: 'a2a2c5ec-7eb3-4c7e-8615-9ab49343ed93'
    updated_by: 'a2a2c5ec-7eb3-4c7e-8615-9ab49343ed93'
    created_date: '2016-01-21 23:48:32.511-07'
    updated_date: '2016-01-21 23:48:32.511-07'
  user:
    id: &user_user_id '845c2609-f51c-4158-91e2-83765b40a272'
    name: 'Test User'
    raw_email: 'testing2@consumr-project.org'
    role: 'user'
    created_by: 'a2a2c5ec-7eb3-4c7e-8615-9ab49343ed93'
    updated_by: 'a2a2c5ec-7eb3-4c7e-8615-9ab49343ed93'
    created_date: '2016-01-21 23:48:32.511-07'
    updated_date: '2016-01-21 23:48:32.511-07'

company:
  id: &company_id 'e68a1d8e-256e-4dcd-b111-f7dd0e7f63e4'
  name: 'Company for Integration Testing'

events:
  - id: 'f0daa99e-76d3-46df-a763-3317199e52b2'
    title: 'test event 1'
    date: '2016-03-10 18:18:34.841703-07'
    sentiment: 'positive'
    logo: 'none'
    _force_create: true

  - id: '1ee4f628-c99d-42ba-9613-e41f7b8c176a'
    title: 'test event 2'
    date: '2016-03-10 18:18:34.841703-07'
    sentiment: 'neutral'
    logo: 'none'
    _force_create: true

  - id: '3b54b2bc-766d-4360-a881-73877ea9100b'
    title: 'test event 3'
    date: '2016-03-10 18:18:34.841703-07'
    sentiment: 'negative'
    logo: 'none'
    _force_create: true

  - id: '3a177113-5fba-490a-a348-2673699c2c9a'
    title: 'test event 4'
    date: '2016-03-10 18:18:34.841703-07'
    sentiment: 'neutral'
    logo: 'none'
    _force_create: true

  - id: '585594f7-ad58-4800-bda4-75ee11e00a34'
    title: 'test event 5'
    date: '2016-03-10 18:18:34.841703-07'
    sentiment: 'positive'
    logo: 'none'
    _force_create: true

  - id: '7538e544-76fe-497c-bda6-b52f8f8db057'
    title: 'test event 6'
    date: '2016-03-10 18:18:34.841703-07'
    sentiment: 'positive'
    logo: 'none'
    _force_create: true

tags:
  - id: '85963fe7-530f-411b-938a-fd5efcfa4cc0'
    approved: true
    'en-US': 'test tag 1'

  - id: 'e53248ec-1dce-490a-8d4a-d02550107a66'
    approved: true
    'en-US': 'test tag 2'

  - id: '4f33af98-783e-44fe-ace8-ad05c1e64969'
    approved: true
    'en-US': 'test tag 3'

  - id: 'da6fa54e-94f0-457d-bb7e-41cc2f6d1313'
    approved: true
    'en-US': 'test tag 4'

  - id: '5d7aa7c4-11c2-4c64-83d2-0b50e1c85b0e'
    approved: true
    'en-US': 'test tag 5'

  - id: '84af1f4f-3b01-4459-a61b-9deee097a8a6'
    approved: true
    'en-US': 'test tag 6'

reviews:
  - id: '1fa00a91-f331-47f3-8fcf-c99a5bc9d176'
    user_id: *user_user_id
    company_id: *company_id
    score: 5
    title: 'this is my own review 1'
    summary: 'all of the information about my review 1'
    created_by: *user_user_id
    updated_by: *user_user_id
    created_date: '2016-01-08 23:48:32.511-07'
    updated_date: '2016-01-08 23:48:32.511-07'
  - id: '2fa00a91-f331-47f3-8fcf-c99a5bc9d176'
    user_id: *user_user_id
    company_id: *company_id
    score: 5
    title: 'this is my own review 2'
    summary: 'all of the information about my review 2'
    created_by: *user_user_id
    updated_by: *user_user_id
    created_date: '2016-01-11 23:48:32.511-07'
    updated_date: '2016-01-11 23:48:32.511-07'
  - id: '3fa00a91-f331-47f3-8fcf-c99a5bc9d176'
    user_id: *user_user_id
    company_id: *company_id
    score: 3
    title: 'this is my own review 3'
    summary: 'all of the information about my review 3'
    created_by: *user_user_id
    updated_by: *user_user_id
    created_date: '2016-01-13 23:48:32.511-07'
    updated_date: '2016-01-13 23:48:32.511-07'
  - id: '4fa00a91-f331-47f3-8fcf-c99a5bc9d176'
    user_id: *user_user_id
    company_id: *company_id
    score: 2
    title: 'this is my own review 4'
    summary: 'all of the information about my review 4'
    created_by: *user_user_id
    updated_by: *user_user_id
    created_date: '2016-01-17 23:48:32.511-07'
    updated_date: '2016-01-17 23:48:32.511-07'
  - id: '5fa00a91-f331-47f3-8fcf-c99a5bc9d176'
    user_id: *user_user_id
    company_id: *company_id
    score: 1
    title: 'this is my own review 5'
    summary: 'all of the information about my review 5'
    created_by: *user_user_id
    updated_by: *user_user_id
    created_date: '2016-01-21 23:48:32.511-07'
    updated_date: '2016-01-21 23:48:32.511-07'

review_usefulness:
  - review_id: '4fa00a91-f331-47f3-8fcf-c99a5bc9d176'
    user_id: *user_user_id
    score: 1
    created_by: *user_user_id
    updated_by: *user_user_id
    created_date: '2016-01-21 23:48:32.511-07'
    updated_date: '2016-01-21 23:48:32.511-07'
  - review_id: '4fa00a91-f331-47f3-8fcf-c99a5bc9d176'
    user_id: *user_admin_id
    score: 1
    created_by: *user_admin_id
    updated_by: *user_admin_id
    created_date: '2016-01-21 23:48:32.511-07'
    updated_date: '2016-01-21 23:48:32.511-07'
  - review_id: '5fa00a91-f331-47f3-8fcf-c99a5bc9d176'
    user_id: *user_user_id
    score: 1
    created_by: *user_user_id
    updated_by: *user_user_id
    created_date: '2016-01-21 23:48:32.511-07'
    updated_date: '2016-01-21 23:48:32.511-07'

questions:
  - id: '7c943a56-9404-4cf7-b656-b5c936bb0a19'
    company_id: *company_id
    title: 'my own question'
    answer: 'here you go'
    answered_by: *user_user_id
    answered_date: '2016-01-21 23:48:32.511-07'
    approved: true
    approved_by: *user_admin_id
    approved_date: '2016-01-21 23:48:32.511-07'
    created_by: *user_user_id
    updated_by: *user_user_id
    created_date: '2016-01-21 23:48:32.511-07'
    updated_date: '2016-01-21 23:48:32.511-07'
  - id: '1ef44bb9-1e80-4723-b07e-798337213a48'
    company_id: *company_id
    title: 'my own question'
    answer: 'here you go'
    answered_by: *user_user_id
    answered_date: '2016-01-21 23:48:32.511-07'
    approved: true
    approved_by: *user_admin_id
    approved_date: '2016-01-21 23:48:32.511-07'
    created_by: *user_user_id
    updated_by: *user_user_id
    created_date: '2016-01-21 23:48:32.511-07'
    updated_date: '2016-01-21 23:48:32.511-07'
  - id: 'b1eef69b-a9dc-424e-b40f-e422397d6333'
    company_id: *company_id
    title: 'my own question'
    answer: 'here you go'
    answered_by: *user_user_id
    answered_date: '2016-01-21 23:48:32.511-07'
    approved: true
    approved_by: *user_admin_id
    approved_date: '2016-01-21 23:48:32.511-07'
    created_by: *user_user_id
    updated_by: *user_user_id
    created_date: '2016-01-21 23:48:32.511-07'
  - id: '4f73a49e-5ef2-465d-b013-3a34e54f8193'
    company_id: *company_id
    title: 'my own question'
    answer: 'here you go'
    answered_by: *user_user_id
    answered_date: '2016-01-21 23:48:32.511-07'
    approved: true
    approved_by: *user_admin_id
    approved_date: '2016-01-21 23:48:32.511-07'
    created_by: *user_user_id
    updated_by: *user_user_id
    created_date: '2016-01-21 23:48:32.511-07'
    updated_date: '2016-01-21 23:48:32.511-07'

feedback:
  - id: '0e701113-adeb-4d4b-88c7-3c1ea0a0e45a'
    referrer: 'http://...'
    user_id: *user_admin_id
    type: 'question'
    message: 'here is my message 1'
    created_by: *user_admin_id
    updated_by: *user_admin_id
    created_date: '2016-01-21 23:48:32.511-07'
    updated_date: '2016-01-21 23:48:32.511-07'
  - id: '52148948-d49a-4d21-8d2a-c6babba2176c'
    referrer: 'http://...'
    user_id: *user_admin_id
    type: 'question'
    message: 'here is my message 2'
    created_by: *user_admin_id
    updated_by: *user_admin_id
    created_date: '2016-01-21 23:48:32.511-07'
    updated_date: '2016-01-21 23:48:32.511-07'
  - id: '2226947a-63bb-423b-968b-025f3a8b73fa'
    referrer: 'http://...'
    user_id: *user_admin_id
    type: 'question'
    message: 'here is my message 3'
    created_by: *user_admin_id
    updated_by: *user_admin_id
    created_date: '2016-01-21 23:48:32.511-07'
    updated_date: '2016-01-21 23:48:32.511-07'
  - id: 'edc8b1ed-e483-439b-afc1-6bceab622ce2'
    referrer: 'http://...'
    user_id: *user_admin_id
    type: 'question'
    message: 'here is my message 4'
    created_by: *user_admin_id
    updated_by: *user_admin_id
    created_date: '2016-01-21 23:48:32.511-07'
    updated_date: '2016-01-21 23:48:32.511-07'
