CRUD: &CRUD [create, retrieve, update, delete]

roles:
  - admin
  - guest
  - user

permissions:
  company: [create, retrieve, update, delete, follow]
  event: *CRUD
  feedback: *CRUD
  product: *CRUD
  question: *CRUD
  review: *CRUD
  tag: [create, retrieve, update, delete, follow]
  user: [create, retrieve, update, delete, follow]
  token: [create]
  beta_email: [create, retrieve, update]

grants:
  guest:
    - retrieve_company
    - retrieve_event
    - retrieve_product
    - retrieve_question
    - retrieve_review
    - retrieve_tag
    - retrieve_user

  user:
    - guest
    - create_company
    - create_event
    - create_feedback
    - create_product
    - create_question
    - create_review
    - create_tag
    - follow_company
    - follow_tag
    - follow_user
    - update_company
    - update_event
    - update_product
    - update_question
    - update_review
    - update_tag

  admin:
    - user
    - create_beta_email
    - create_token
    - create_user
    - delete_company
    - delete_event
    - delete_feedback
    - delete_product
    - delete_question
    - delete_review
    - delete_tag
    - delete_user
    - retrieve_beta_email
    - retrieve_feedback
    - update_beta_email
