roles:
  - admin
  - user
  - guest

permissions:
  CRUD: &CRUD [create, retrieve, update, delete]
  user: [create, retrieve, update, delete, follow]
  feedback: *CRUD
  tag: [create, retrieve, update, delete, follow]
  product: *CRUD
  company: [create, retrieve, update, delete, follow]
  event: *CRUD
  review: *CRUD
  question: *CRUD

grants:
  guest:
    - retrieve_user
    - retrieve_tag
    - retrieve_product
    - retrieve_company
    - retrieve_event
    - retrieve_review
    - retrieve_question

  user:
    - guest
    - create_feedback
    - create_tag
    - update_tag
    - create_product
    - update_product
    - create_company
    - update_company
    - create_event
    - update_event
    - create_review
    - update_review
    - create_question
    - update_question
    - follow_user
    - follow_tag
    - follow_company

  admin:
    - user
    - create_user
    - retrieve_feedback
    - delete_feedback
    - delete_user
    - delete_tag
    - delete_product
    - delete_company
    - delete_event
    - delete_review
    - delete_question
