models:
  - name: companies
    soft_delete: true

  - name: events
    label: title

  - name: event_sources
    label: title
    fields: [ summary ]

  - name: users
    fields: [ email, title, company_name ]
    soft_delete: true

  - name: tags
    label: '"en-US"'
    soft_delete: true

  - name: products
    label: '"en-US"'
    soft_delete: true
