#!/bin/bash

# docker
sudo apt-get update
sudo apt-get install git apt-transport-https ca-certificates -y
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 \
    --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

sudo su
echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > \
    /etc/apt/sources.list.d/docker.list
exit
sudo apt-get update
sudo apt-get install docker-engine -y

# docker-compose
sudo su
sudo curl -L https://github.com/docker/compose/releases/download/1.6.0/docker-compose-`uname -s`-`uname -m` > \
    /usr/local/bin/docker-compose
exit
sudo chmod +x /usr/local/bin/docker-compose

# consurm-project
git clone https://github.com/consumr-project/cp
