#!/bin/bash

source $(dirname "$0")/cli.sh

case "$1" in
    base)
        ./script/generate app:user
        ./script/generate app:tags
        ./script/generate app:products
        ;;

    test)
        ./script/generate test:user
        ;;

    heroku)
        use heroku:env
        use heroku:addons
        use heroku:buildpacks

        heroku:buildpack heroku/nodejs
        heroku:addon heroku-postgresql hobby-dev

        heroku:envar CLIENT_DEBUG_INFO 1
        heroku:envar CP_ADMIN_EMAILS
        heroku:envar CP_AUTH_LOCKDOWN 1
        heroku:envar CP_COOKIE_KEY
        heroku:envar CP_CRYPTO_AUTH_TOKEN_KEY
        heroku:envar CP_CRYPTO_USER_EMAIL_KEY
        heroku:envar CP_ENV
        heroku:envar CP_SESSION_KEY
        heroku:envar CP_URL
        heroku:envar DATABASE_URL
        heroku:envar ELASTICSEARCH_HOST
        heroku:envar EMAIL_SERVICE_HOST
        heroku:envar EMAIL_SERVICE_PASS
        heroku:envar EMAIL_SERVICE_USER
        heroku:envar EMBEDLY_API_KEY
        heroku:envar GOOGLE_ANALYTICS_ACCOUNT_ID
        heroku:envar GOOGLE_RECAPTCHA_KEY
        heroku:envar GOOGLE_RECAPTCHA_SECRET
        heroku:envar LINKEDIN_CLIENT_ID
        heroku:envar LINKEDIN_CLIENT_SECRET
        heroku:envar LOG_LEVEL
        heroku:envar MONGO_URL
        heroku:envar NODE_ENV development
        heroku:envar NODE_MODULES_CACHE false
        heroku:envar NPM_CONFIG_PRODUCTION false
        heroku:envar ROLLBAR_TOKEN
        heroku:envar SERVER_JIT_COMPRESSION true
        heroku:envar SERVER_VIEW_CACHING true
        heroku:envar TRELLO_BOARD_ID
        heroku:envar TRELLO_KEY
        heroku:envar FILES_AVATARS_IMGUR_ALBUM_ID
        heroku:envar FILES_AVATARS_IMGUR_CLIENT_ID
        heroku:envar FILES_AVATARS_IMGUR_PASSWORD
        heroku:envar FILES_AVATARS_IMGUR_USERNAME
        heroku:envar TRELLO_LIST_ID
        heroku:envar TRELLO_TOKEN
        ;;

    postgres)
        host=$(url:parse $DATABASE_URL hostname)
        port=$(url:parse $DATABASE_URL port)
        auth=$(url:parse $DATABASE_URL auth)
        echo "$host:$port:*:$auth"
        ;;

    postgres-2)
        echo "$POSTGRES_HOST:5432:$POSTGRES_DB:$POSTGRES_USER:$POSTGRES_PASSWORD"
        ;;

    env)
        [ -f .env ] && source .env
        cat <<EOF > .env
CLIENT_DEBUG_INFO=$CLIENT_DEBUG_INFO
CP_ADMIN_EMAILS=$CP_ADMIN_EMAILS
CP_AUTH_LOCKDOWN=$CP_AUTH_LOCKDOWN
CP_COOKIE_KEY=$CP_COOKIE_KEY
CP_CRYPTO_AUTH_TOKEN_KEY=$CP_CRYPTO_AUTH_TOKEN_KEY
CP_CRYPTO_USER_EMAIL_KEY=$CP_CRYPTO_USER_EMAIL_KEY
CP_ENV=$CP_ENV
CP_SESSION_KEY=$CP_SESSION_KEY
CP_URL=$CP_URL
DATABASE_URL=$DATABASE_URL
DEBUG=$DEBUG
ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
EMAIL_SERVICE_HOST=$EMAIL_SERVICE_HOST
EMAIL_SERVICE_PASS=$EMAIL_SERVICE_PASS
EMAIL_SERVICE_USER=$EMAIL_SERVICE_USER
EMBEDLY_API_KEY=$EMBEDLY_API_KEY
FILES_AVATARS_IMGUR_ALBUM_ID=$FILES_AVATARS_IMGUR_ALBUM_ID
FILES_AVATARS_IMGUR_CLIENT_ID=$FILES_AVATARS_IMGUR_CLIENT_ID
FILES_AVATARS_IMGUR_PASSWORD=$FILES_AVATARS_IMGUR_PASSWORD
FILES_AVATARS_IMGUR_USERNAME=$FILES_AVATARS_IMGUR_USERNAME
GOOGLE_ANALYTICS_ACCOUNT_ID=$GOOGLE_ANALYTICS_ACCOUNT_ID
GOOGLE_RECAPTCHA_KEY=$GOOGLE_RECAPTCHA_KEY
GOOGLE_RECAPTCHA_SECRET=$GOOGLE_RECAPTCHA_SECRET
LINKEDIN_CLIENT_ID=$LINKEDIN_CLIENT_ID
LINKEDIN_CLIENT_SECRET=$LINKEDIN_CLIENT_SECRET
LOG_LEVEL=$LOG_LEVEL
MONGO_URL=$MONGO_URL
NODE_ENV=$NODE_ENV
NPM_CONFIG_PRODUCTION=false
ROLLBAR_TOKEN=$ROLLBAR_TOKEN
SERVER_JIT_COMPRESSION=$SERVER_JIT_COMPRESSION
SERVER_VIEW_CACHING=$SERVER_VIEW_CACHING
TRELLO_BOARD_ID=$TRELLO_BOARD_ID
TRELLO_KEY=$TRELLO_KEY
TRELLO_LIST_ID=$TRELLO_LIST_ID
TRELLO_TOKEN=$TRELLO_TOKEN
EOF

        echo save .env file
        ;;

    *)
        echo invalid option
        echo "usage: $0 <command>"
        echo
        echo commands:
        echo "    - base              generate data for the app to be useful"
        echo "    - test              generate data for the app to be testable"
        echo "    - heroku            configure your heroku instance to be able to run the app"
        echo "    - postgres          generate content for a .pgpass file using the DATABASE_URL variable"
        echo "    - postgres-2        generate content for a .pgpass file using the POSTGRES_ variables"
        echo "    - env               generate a .env file"
        exit 1
        ;;
esac
