#!/bin/bash

source $(dirname "$0")/cli.sh

case "$1" in
    base)
        ./script/generate app:user
        ./script/generate app:tags
        ./script/generate app:products
        ;;

    test)
        ./script/generate test:user
        ;;

    heroku)
        use heroku:env
        use heroku:addons
        use heroku:buildpacks

        heroku:buildpack heroku/nodejs
        heroku:addon heroku-postgresql hobby-dev

        heroku:envar CP_COOKIE_KEY
        heroku:envar CP_SESSION_KEY
        heroku:envar DATABASE_URL
        heroku:envar ELASTICSEARCH_HOST
        heroku:envar EMBEDLY_API_KEY
        heroku:envar GOOGLE_ANALYTICS_ACCOUNT_ID
        heroku:envar LINKEDIN_CLIENT_ID
        heroku:envar LINKEDIN_CLIENT_SECRET
        heroku:envar MONGO_URL
        heroku:envar NODE_ENV development
        heroku:envar NODE_MODULES_CACHE false
        heroku:envar NPM_CONFIG_PRODUCTION false
        heroku:envar ROLLBAR_TOKEN
        heroku:envar SERVER_JIT_COMPRESSION true
        heroku:envar TRELLO_BOARD_ID
        heroku:envar TRELLO_KEY
        heroku:envar TRELLO_LIST_ID
        heroku:envar TRELLO_TOKEN
        ;;

    postgres)
        host=$(url:parse $DATABASE_URL hostname)
        port=$(url:parse $DATABASE_URL port)
        auth=$(url:parse $DATABASE_URL auth)
        echo "$host:$port:*:$auth"
        ;;

    *)
        assert EMBEDLY_API_KEY $(test ! -z $EMBEDLY_API_KEY)
        assert GOOGLE_ANALYTICS_ACCOUNT_ID $(test ! -z $GOOGLE_ANALYTICS_ACCOUNT_ID)
        assert LINKEDIN_CLIENT_ID $(test ! -z $LINKEDIN_CLIENT_ID)
        assert LINKEDIN_CLIENT_SECRET $(test ! -z $LINKEDIN_CLIENT_SECRET)
        assert ROLLBAR_TOKEN $(test ! -z $ROLLBAR_TOKEN)
        assert TRELLO_BOARD_ID $(test ! -z $TRELLO_BOARD_ID)
        assert TRELLO_KEY $(test ! -z $TRELLO_KEY)
        assert TRELLO_LIST_ID $(test ! -z $TRELLO_LIST_ID)
        assert TRELLO_TOKEN $(test ! -z $TRELLO_TOKEN)
        ;;
esac
