#!/bin/bash

source $(dirname "$0")/cli.sh

case "$1" in
    base)
        ./script/generate app:user
        ./script/generate app:tags
        ./script/generate app:products
        ;;

    test)
        ./script/generate test:user
        ;;

    heroku)
        use heroku:env
        use heroku:addons
        use heroku:buildpacks

        heroku:buildpack heroku/nodejs
        heroku:addon heroku-postgresql hobby-dev

        heroku:envar CP_COOKIE_KEY
        heroku:envar CP_SESSION_KEY
        heroku:envar CP_CRYPTO_AUTH_TOKEN_KEY
        heroku:envar CP_CRYPTO_USER_EMAIL_KEY
        heroku:envar DATABASE_URL
        heroku:envar ELASTICSEARCH_HOST
        heroku:envar EMBEDLY_API_KEY
        heroku:envar GOOGLE_ANALYTICS_ACCOUNT_ID
        heroku:envar LINKEDIN_CLIENT_ID
        heroku:envar LINKEDIN_CLIENT_SECRET
        heroku:envar MONGO_URL
        heroku:envar NODE_ENV development
        heroku:envar NODE_MODULES_CACHE false
        heroku:envar NPM_CONFIG_PRODUCTION false
        heroku:envar ROLLBAR_TOKEN
        heroku:envar SERVER_JIT_COMPRESSION true
        heroku:envar TRELLO_BOARD_ID
        heroku:envar TRELLO_KEY
        heroku:envar TRELLO_LIST_ID
        heroku:envar TRELLO_TOKEN
        ;;

    postgres)
        host=$(url:parse $DATABASE_URL hostname)
        port=$(url:parse $DATABASE_URL port)
        auth=$(url:parse $DATABASE_URL auth)
        echo "$host:$port:*:$auth"
        ;;

    postgres-2)
        echo "$POSTGRES_HOST:5432:$POSTGRES_DB:$POSTGRES_USER:$POSTGRES_PASSWORD"
        ;;

    env)
        cat <<EOF > .env
NPM_CONFIG_PRODUCTION=false
CP_COOKIE_KEY=$CP_COOKIE_KEY
CP_CRYPTO_AUTH_TOKEN_KEY=$CP_CRYPTO_AUTH_TOKEN_KEY
CP_CRYPTO_USER_EMAIL_KEY=$CP_CRYPTO_USER_EMAIL_KEY
CP_SESSION_KEY=$CP_SESSION_KEY
EMBEDLY_API_KEY=$EMBEDLY_API_KEY
GOOGLE_ANALYTICS_ACCOUNT_ID=$GOOGLE_ANALYTICS_ACCOUNT_ID
LINKEDIN_CLIENT_ID=$LINKEDIN_CLIENT_ID
LINKEDIN_CLIENT_SECRET=$LINKEDIN_CLIENT_SECRET
NODE_ENV=$NODE_ENV
ROLLBAR_TOKEN=$ROLLBAR_TOKEN
SERVER_JIT_COMPRESSION=$SERVER_JIT_COMPRESSION
TRELLO_BOARD_ID=$TRELLO_BOARD_ID
TRELLO_KEY=$TRELLO_KEY
TRELLO_LIST_ID=$TRELLO_LIST_ID
TRELLO_TOKEN=$TRELLO_TOKEN
EOF

        echo save .env file
        ;;

    *)
        echo wat?
        exit 1
        ;;
esac
