#!/usr/bin/env node

'use strict';

require('dotenv').config();

var config = require('acm'),
    varname = process.argv[2];

varname && console.log('var %s =', varname);

console.log({
    features: config('features'),

    beta: {
        lockdown: !!config('cp.auth.lockdown'),
    },

    google: {
        analytics: {
            gaid: config('google.analytics.account_id')
        },
        recaptcha: {
            key: config('google.recaptcha.key')
        },
    },

    environment: {
        name: config('cp.env') || 'development',
    },

    rollbar: {
        token: config('rollbar.token'),
    },

    locate: {
        dateFormat: config('locale.dateFormat'),
    },
});

varname && console.log(';');
