#!/bin/bash

actually_run_migration() {
    local passfile="~/.pgpass"

    if [ "$EUID" -eq 0 ]; then
        passfile="/root/.pgpass"
    fi

    touch $passfile
    chmod 0600 $passfile

    echo saving info to $passfile
    ./script/bootstrap postgres-2 > $passfile

    echo running migrations
    ./script/migration run

    echo bootstrapping app
    ./script/bootstrap base
}

if which docker-compose &> /dev/null; then
    docker-compose run --rm server ./script/docker-database-setup
else
    time actually_run_migration
fi
