#!/bin/bash

migrations_command=$(cat << COMMAND
touch ~/.pgpass;
chmod 0600 ~/.pgpass;
./script/bootstrap postgres > ~/.pgpass;
./script/migration run;
COMMAND)

./script/compile-project-stamp > stamp.json
git commit -m "[skip ci] stamp" stamp.json
git push origin master
git push heroku master
heroku run "$(echo $migrations_command)"
