#!/usr/bin/env node

'use strict';

const clone = require('lodash/clone');
const yaml = require('yamljs');
const fs = require('fs');

var argv = clone(process.argv);

argv.shift();
argv.shift();
console.log('checking %s files', argv.length);
argv.forEach(file => {
    try {
        yaml.parse(fs.readFileSync(file).toString());
    } catch (err) {
        console.log('error parsing %s', file);
        process.exit(1);
    }
});
