#!/usr/bin/env node

require('dotenv').config();

const program = require('commander');
const email = require('../build/notification/email');
const normalize_i18n = require('../build/strings').normalize_i18n;

/**
 * @param {Error} [err]
 */
function err_exit(err) {
    console.error('error sendig email')

    if (err) {
        console.error(err);
    }

    process.exit(1);
}

/**
 * @param {Object(to: string)} cmd
 * @return {Function}
 */
function ok_exit(cmd) {
    return function () {
        console.log('successfully sent email (%s) to %s',
            normalize_i18n(cmd.lang), cmd.to);

        process.exit(0);
    }
}

/**
 * @param {Object(to: string, name: string, lang?: string)} cmd
 * @param {Function} email_fn
 * @return {void}
 */
function send(cmd, email_fn) {
    if (!cmd.to) {
        console.error('"to" value is required');
        err_exit();
    } else if (!cmd.name) {
        console.error('"name" value is required');
        err_exit();
    } else {
        email_fn(cmd.to, cmd.name, cmd.lang)
            .then(ok_exit(cmd))
            .catch(err_exit);
    }
}

program
    .command('welcome')
    .option('-t, --to <email>', 'email address this email should be sent to')
    .option('-n, --name <name>', 'name of person email is going to')
    .option('-l, --lang [language]', 'use a specific language')
    .description('send a welcome email')
    .action(cmd => send(cmd, email.send.welcome));

program.parse(process.argv);

if (!process.argv.slice(2).length) {
    program.outputHelp();
}
