#!/bin/bash

tape=./node_modules/.bin/tape
tap_diff=./node_modules/.bin/tap-diff
protractor=./test/e2e/node_modules/.bin/protractor

tatatape() {
    $tape $@ | $tap_diff
}

case "$1" in
    e2e)
        $protractor config/protractor.js
        ;;

    unit)
        tatatape $(find test/src -name "*.js")
        ;;

    external)
        tatatape $(find test/external -name "*.js")
        ;;

    integration)
        tatatape $(find test/integration -name "*.js")
        ;;

    test/*)
        tatatape "$@"
        ;;

    *)
        tatatape \
            $(find test/external -name "*.js") \
            $(find test/integration -name "*.js") \
            $(find test/src -name "*.js")
        ;;
esac
