#!/bin/bash

function log() {
    echo "  - $@"
}

function query-service() {
    local src=node_modules/query-service
    local tmp=.query-service

    log "moving local query-service"
    rm -rf $tmp
    mkdir $tmp
    cp -r $src/* $tmp
    cd $tmp

    log "resetting npm modules"
    rm -rf node_modules
    npm install &> /dev/null

    log "updating database"
    make migrate

    log "cleaning up"
    cd -
    rm -rf $tmp
}

if [ ! -z "$DATABASE_URL" ]; then
    time query-service
else
    log "no DATABASE_URL found, skipping migrations"
fi
