#!/usr/bin/env node

'use strict';

var config = require('acm'),
    varname = process.argv[2];

varname && console.log('var %s =', varname);

console.log({
    features: config('features'),
    analytics: { gaid: config('google.analytics.account_id') },
    enviroment: { name: config('node.env') || 'development' },
    rollbar: { token: config('rollbar.token') },
    locate: { dateFormat: config('locale.dateFormat') }
});

varname && console.log(';');
