#!/usr/bin/env node

'use strict';

var config = require('acm'),
    action = process.argv[2],
    varname = process.argv[3];

switch (action) {
    case '--typings':
        console.log('declare var %s: {', varname);
        console.log('    embedly: { key: string; };');
        console.log('    firebase: { url: string; };');
        console.log('    locale: { dateFormat: string; };');
        console.log('};');
        break;

    case '--config':
        varname && console.log('var %s =', varname);

        console.log({
            embedly: { key: config.get('embedly.api.key') },
            firebase: { url: config.get('firebase.url') },
            locate: { dateFormat: config.get('locale.dateFormat') }
        });

        varname && console.log(';');
        break;
}
