#!/usr/bin/env node

'use strict'

var Firebase = require('firebase');

var csv = require('fast-csv'),
    config = require('acm'),
    hash = require('lodash/utility/uniqueId'),
    read = require('fs').createReadStream;

var firebase = new Firebase(config('firebase.url'));

read('./docs/data/tags.csv').pipe(csv({ headers: true }))
    .on('end', done('tags'))
    .on('data', push(firebase.child('tag')));

/**
 * @param {Firebase} store
 * @return {Function<Object>}
 */
function push(store) {
    return function (obj) {
        var url = store.path.o.join('/'),
            id = hash();

        console.log('pushing %s to %s', id, url);
        store.push(obj, function (err) {
            if (err) {
                console.error('error pushing %s to %s', id, url);
            } else {
                console.log('done pushing %s to %s', id, url);
            }
        });
    };
}

/**
 * @param {String} label
 * @return {Function}
 */
function done(label) {
    return function () {
        console.log('done processing %s file', label);
    };
}
