#!/bin/bash

tape=./node_modules/.bin/tape
protractor=./node_modules/.bin/protractor

case "$1" in
    e2e)
        $protractor config/protractor.js
        ;;

    unit)
        $tape $(find test/src -name "*.js")
        ;;

    external)
        $tape $(find test/external -name "*.js")
        ;;

    integration)
        $tape $(find test/integration -name "*.js")
        ;;

    release)
        make lint build test && ./scripts/release
        ;;

    *)
        $tape \
            $(find test/external -name "*.js") \
            $(find test/integration -name "*.js") \
            $(find test/src -name "*.js")
        ;;
esac
